"""Add user roles

Revision ID: e6bd3297e2c8
Revises: b968f779733d
Create Date: 2021-12-10 12:14:13.452768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bd3297e2c8'
down_revision = 'b968f779733d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
