"""Add index to slug in gig

Revision ID: 2bf843bdd622
Revises: 256e1068c521
Create Date: 2021-12-10 21:18:02.340022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf843bdd622'
down_revision = '256e1068c521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gigs_slug'), 'gigs', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gigs_slug'), table_name='gigs')
    # ### end Alembic commands ###
