"""Adding account activation

Revision ID: 8cfc72716333
Revises: 8663c739b8d7
Create Date: 2021-12-13 22:06:19.494188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfc72716333'
down_revision = '8663c739b8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('activation_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activation_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_sent_at')
    op.drop_column('users', 'activation_hash')
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###
