"""Add remember hashes

Revision ID: b968f779733d
Revises: d8d91197d7d9
Create Date: 2021-12-08 13:31:32.744296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b968f779733d'
down_revision = 'd8d91197d7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remember_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remembers_user_id'), 'remembers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remembers_user_id'), table_name='remembers')
    op.drop_table('remembers')
    # ### end Alembic commands ###
